server:
  port: 3000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:PORT/DATABASE
    username: USERNAME
    password: PASSWORD
  jpa:
    hibernate:
      ddl-auto: create

upload.folder: YOUR_PATH/TO/UPLOAD/FOLDER/assets/books
