server:
  port: 5000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:PORT/DATABASE
    username: USERNAME
    password: PASSWORD
  jpa:
    hibernate:
      ddl-auto: create

upload.folder: assets/books
jwt.secret: YOUR_JWT_SECRET_FOR_GENERATING_TOKENS
