#!/bin/bash

declare -a DUMMIES=(
    "{\"title\": \"Rewind It Back\",\"published\": \"April 24, 2025\",\"author\": \"Liz Tomforde\",\"genre\": \"Romance Sports Romance Sports Contemporary\",\"format\": \"-\",\"isbn\": \"9781399746427\",\"description\": \"-\"}"
    "{\"title\": \"The Message\",\"published\": \"October 1, 2024\",\"author\": \"Ta-Nehisi Coates\",\"genre\": \"Nonfiction Essays Politics History Audiobook Race Memoir\",\"format\": \"232 pages, Hardcover\",\"isbn\": \"9780593230381 \",\"description\": \"Ta-Nehisi Coates originally set off to write a book about writing, in the tradition of Orwell classic Politics and the English Language, but found himself grappling with deeper questions about how our stories our reporting and imaginative narratives and mythmaking expose and distort our realities.\n\nThe first of the book three intertwining essays is set in Dakar, Senegal. Despite being raised as a strict Afrocentrist, Coates had never set foot on the African continent until now. He roams the steampunk city of old traditions and new machinery, but everywhere he goes he feels as if he in two places at once: a modern city in Senegal and a mythic kingdom in his mind. Finally, he travels to the slave castles off the coast and has his own reckoning with the legacy of the Afrocentric dream.\n\nHe takes readers along with him to Columbia, South Carolina, where he meets an educator whose job is threatened for teaching one of Coates own books. There he discovers a community of mostly white supporters who were transformed by the racial reckoning of 2020. But he also explores the backlash to this reckoning and the deeper myths of the community a capital of the Confederacy with statues of segregationists looming over its public squares.\n\nAnd in Palestine, Coates discovers the devastating gap between the narratives wee accepted and the clashing reality of life on the ground. He meets with activists and dissidents, Israelis and Palestinians the old, who remember their dispossessions on two continents, and the young, who have only known struggle and disillusionment. He travels into Jerusalem, the heart of Zionist mythology, and to the occupied territories, where he sees the reality the myth is meant to hide. It is this hidden story that draws him in and profoundly changes him and makes the war that would soon come all the more devastating.\n\nWritten at a dramatic moment in American and global life, this work from one of the country most important writers is about the urgent need to untangle ourselves from the destructive nationalist myths that shape our world and our own souls and embrace the liberating power of even the most difficult truths.\"}"
    "{\"title\": \"Onyx Storm\",\"published\": \"January 21, 2025\",\"author\": \"Rebecca Yarros\",\"genre\": \"Fantasy Romantasy Romance Dragons Fantasy Romance Fiction Adult\",\"format\": \"Hardcover\",\"isbn\": \"9781649374189\",\"description\": \"Get ready to fly or die in the breathtaking follow-up to Fourth Wing and Iron Flame from#1 New York Times bestselling author Rebecca Yarros.\n\nAfter nearly eighteen months at Basgiath War College, Violet Sorrengail knows there no more time for lessons.\nNo more time for uncertainty.\nBecause the battle has truly begun; and with enemies closing in from outside their walls and within their ranks, it impossible to know who to trust.\nNow Violet must journey beyond the failing Aretian wards to seek allies from unfamiliar lands to stand with Navarre.\nThe trip will test every bit of her wit, luck, and strength, but she will do anything to save what she loves - her dragons, her family, her home, and him.\nEven if it means keeping a secret so big, it could destroy everything.\nThey need an army.\nThey need power.\nThey need magic.\nAnd they need the one thing only Violet can find the truth.\nBut a storm is coming... and not everyone can survive its wrath\"}"
    "{\"title\": \"Sunrise on the Reaping\",\"published\": \"March 18, 2025\",\"author\": \"Suzanne Collins\",\"genre\": \"Dystopia Young Adult Fantasy Fiction\",\"format\": \"400 pages, Hardcover\",\"isbn\": \"9781546171461 \",\"description\": \"As the day dawns on the fiftieth annual Hunger Games, fear grips the districts of Panem. This year, in honor of the Quarter Quell, twice as many tributes will be taken from their homes.\n\nBack in District 12, Haymitch Abernathy is trying not to think too hard about his chances. All he cares about is making it through the day and being with the girl he loves.\n\nWhen Haymitch's name is called, he can feel all his dreams break. He's torn from his family and his love, shuttled to the Capitol with the three other District 12 a young friend who's nearly a sister to him, a compulsive oddsmaker, and the most stuck-up girl in town.\n\nAs the Games begin, Haymitch understands he's been set up to fail. But there's something in him that wants to fight . . . and have that fight reverberate far beyond the deadly arena.\"}"
    "{\"title\": \"Reckless\",\"published\": \"July 2, 2024\",\"author\": \"Lauren Roberts\",\"genre\": \"Fantasy Romance Romantasy Young Adult\",\"format\": \"396 pages, Kindle Edition\",\"isbn\": \"9781728297033\",\"description\": \"After surviving the Purging Trials, Ordinary-born Paedyn Gray has killed the King, and kickstarted a Resistance throughout the land. Now she running from the one person she had wanted to run to.\n\nKai Azer is now Ilya Enforcer, loyal to his brother Kitt, the new King. He has vowed to find Paedyn and bring her to justice.\n\nAcross the deadly Scorches, and deep into the hostile city of Dor, Kai pursues the one person he wishes he didn have to. But in a city without Elites, the balance between the hunter and hunted shifts and the battle between duty and desire is deadly.\n\nBe swept away by this kiss-or-kill romantasy trilogy taking the world by storm.\"}"
    "{\"title\": \"Framed: Astonishing True Stories of Wrongful Convictions\",\"published\": \"October 15, 2024\",\"author\": \"John Grisham, Jim McCloskey\",\"genre\": \"Nonfiction True Crime Crime History Audiobook Mystery Short Stories\",\"format\": \"368 pages, Hardcover\",\"isbn\": \"9780385550444\",\"description\": \"In his first work of nonfiction since The Innocent Man, #1 bestselling author John Grisham and Centurion Ministries Founder Jim McCloskey share ten harrowing true stories of wrongful convictions. Impeccably researched and grippingly told, Framed offers an inside look at the injustice faced by the victims of the United States criminal justice system.\n\nA fundamental principle of our legal system is a presumption of innocence, but once someone has been found guilty there is very little room to prove doubt. Framed shares ten true stories of men who were innocent but found guilty and forced to sacrifice friends, families, wives, and decades of their lives to prison while the guilty parties remained free. In each of the stories, John Grisham and Jim McCloskey recount the dramatic hard-fought battles for exoneration. They take a close look at what leads to wrongful convictions in the first place, and the racism, misconduct, flawed testimony, and the corrupt court system that can make them so hard to reverse.\n\nTold with page-turning suspense as only John Grisham can deliver, Framed is the story of overcoming adversity when the battle already seems lost, and the deck is stacked against you.\"}"
)

for (( i=0; i<${#DUMMIES[@]}; i++ ));
do
    curl -H "Content-Type: application/json" \
        -X POST \
        -d "${DUMMIES[$i]}" \
        http://localhost:3000/api/books &
done

declare -a DUMMIES=(
    "{\"username\": \"echidna\", \"displayName\": \"echidna\", \"password\": \"echidna\", \"email\": \"echidna@bookrevu.com\"}"
    "{\"username\": \"admin\", \"displayName\": \"admin\", \"password\": \"admin\", \"email\": \"admin@bookrevu.com\"}"
)

for (( i=0; i<${#DUMMIES[@]}; i++ ));
do
    curl -H "Content-Type: application/json" \
        -X POST \
        -d "${DUMMIES[$i]}" \
        http://localhost:3000/api/users
done
